### ISSUE TITLE
suggestion : option to set week starting at mondays instead of sundays

### ISSUE THREAD

**Issue by paulgreg** [Vifon/TrayCalendar#2]
Thanks for that great project.

Living in France, it would be great if we could set an option to start week at mondays instead of sundays.

**Comment by vifon** [comment]
As far as I'm aware, the GTK calendar widget used here has no option to set the week start from code, instead it uses the locale to decide. Since I also prefer my weeks starting on Mondays, I have a wrapper script that sets the locale with `export LC_TIME='en_GB.UTF-8'` first before starting TrayCalendar. Of course you can use a different locale, as long as it has the behavior you want.

**Comment by paulgreg** [comment]
That’s a very good idea. Thanks :pray:
